# 登陆服务配置
server:
  port: 8001
spring:
  application:
    name: auth-server
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:7878
        port: 9999
eureka:
  client:
    healthcheck:
      enabled: true

